name: Build

on: pull_request

jobs:
  build:
    name: Build for ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Requirements
        run: sudo apt install postgresql libpq-dev && pip install -r requirements.txt
      - name: Lint
        run: env PYTHONPATH=. pylint happex/
  docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build Image
        run: docker build .
